const data = {
    products: [
        {
          _id: '1',
          name: 'T-Shirt',
          category: 'T-Shirt',
          image: '/images/p1.jpg',
          price: 26,
          countInStock: 6,
          brand: 'Vaco',
          rating: 4.5,
          numReviews: 10,
          description: 'Meilleure qualité de coton',
        },
        { 
          _id: '2',
          name: 'Hoodie',
          category: 'Hoodie',
          image: '/images/p2.jpg',
          price: 39,
          countInStock: 0,
          brand: 'Turing',
          rating: 4.5,
          numReviews: 9,
          description: 'Meilleure qualité de coton',
        },
        {
          _id: '3',
          name: 'Sweatshirt',
          category: 'T-Shirt',
          image: '/images/p3.jpg',
          price: 70,
          countInStock: 9,
          brand: ' Strok',
          rating: 4.5,
          numReviews: 14,
          description: 'Meilleure qualité de coton',
        }, 
        {
          _id: '4',
          name: 'T-Shirt',
          category: 'T-Shirt',
          image: '/images/p4.jpg',
          price: 26,
          countInStock: 6,
          brand: 'Cube',
          rating: 4.5,
          numReviews: 8,
          description: 'Meilleure qualité de coton',
        },
        {
          _id: '5',
          name: 'T-Shirt',
          category: 'T-Shirt',
          image: '/images/p5.jpg',
          price: 26,
          countInStock: 6,
          brand: 'Cube',
          rating: 4.5,
          numReviews: 8,
          description: 'Meilleure qualité de coton',
        },
        {
          _id: '6',
          name: 'T-Shirt',
          category: 'T-Shirt',
          image: '/images/p6.jpg',
          price: 26,
          countInStock: 6,
          brand: 'Cube',
          rating: 4.5,
          numReviews: 8,
          description: 'Meilleure qualité de coton',
        },
        {
          _id: '7',
          name: 'T-Shirt',
          category: 'T-Shirt',
          image: '/images/p7.jpg',
          price: 26,
          countInStock: 6,
          brand: 'Cube',
          rating: 4.5,
          numReviews: 8,
          description: 'Meilleure qualité de coton',
        },
        {
          _id: '8',
          name: 'T-Shirt',
          category: 'T-Shirt',
          image: '/images/p8.jpg',
          price: 26,
          countInStock: 6,
          brand: 'Cube',
          rating: 4.5,
          numReviews: 8,
          description: 'Meilleure qualité de coton',
        },
      ],
    };
    export default data;
